Update Sample for Namespace Changes
mspnp/container-apps-fabrikam-dronedelivery pull request #20
Opened 2022-03-10 15:16 UTC by hallihan

Container apps has announced changes to the namespace for the preview service in https://github.com/microsoft/azure-container-apps/issues/109

- Update namespace and version references
- Update to use managedEnvironmentId instead of kubeEnvironmentId
- Update instructions to register Microsoft.App instead of Microsoft.Web

2022-03-10 15:25 UTC, ferantivero requested changes
please let me add two reminders @hallihan

2022-03-10 15:25 UTC, ferantivero commented on container-http.bicep
> +resource containerApp 'Microsoft.App/containerApps@2022-01-01-preview' = {
please let's ensure by the time we merge it is latest one.

2022-03-11 01:30 UTC, hallihan commented on README.md
> +   az provider register --namespace Microsoft.App
According to the announcement this is still required, I'm guessing it will be until closer to GA.

2022-03-11 01:30 UTC, ferantivero approved these changes

2022-03-11 01:32 UTC, merged